#!/bin/bash

# The base name of the output file
output_base="$(dirname "$1")/new_document"

# Create an array to hold the PDF files
pdf_files=()

# Check if only one file is selected and it's a PDF
if [[ $# -eq 1 && "${1##*.}" == "pdf" ]]; then
    # Find a unique name for the output file
    counter=1
    output="${output_base}.pdf"
    while [[ -e "$output" ]]; do
        output="${output_base}(${counter}).pdf"
        let counter++
    done

    cp "$1" "$output"
    exit 0
fi

# Loop over all selected files
for file in "$@"
do
    # Get the file extension
    extension="${file##*.}"

    # Check if the file is an image
    if [[ "$extension" =~ ^(jpg|jpeg|png|gif)$ ]]
    then
        # Convert the image to PDF and add it to the array
        pdf_file="${file%.*}.pdf"
        convert "$file" "$pdf_file"
        pdf_files+=("$pdf_file")
    else
        # Add the PDF file to the array
        pdf_files+=("$file")
    fi
done

# Find a unique name for the output file
counter=1
output="${output_base}.pdf"
while [[ -e "$output" ]]; do
    output="${output_base}(${counter}).pdf"
    let counter++
done

# Merge the PDF files
pdftk "${pdf_files[@]}" cat output "$output"

# Remove individual PDF files
for file in "${pdf_files[@]}"
do
    if [[ "$file" != "$output" ]]; then
        rm "$file"
    fi
done